"""empty message

Revision ID: 379f7ef1f830
Revises: 
Create Date: 2022-10-29 19:08:08.885215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379f7ef1f830'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chofer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('apellido', sa.String(length=250), nullable=True),
    sa.Column('telefono', sa.String(length=250), nullable=True),
    sa.Column('licencia', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remolque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=250), nullable=True),
    sa.Column('placas', sa.String(length=250), nullable=True),
    sa.Column('tipo', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tractor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=250), nullable=True),
    sa.Column('placas', sa.String(length=250), nullable=True),
    sa.Column('marca', sa.String(length=250), nullable=True),
    sa.Column('modelo', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tractor')
    op.drop_table('remolque')
    op.drop_table('chofer')
    # ### end Alembic commands ###
